services:
  device1:
    build: .
    command: python -m app.device.main 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - devnet
    env_file:
      - .env
    environment:
      MODE: http
      TYPE: temp

  device2:
    build: .
    command: python -m app.device.main 
    networks:
      - devnet
    env_file:
      - .env
    environment:
      MODE: mqtt
      TYPE: track
      TRACK_PATH: /app/FlightAware_LVL230K_KMIA_LEBL_20260413.geojson
      TRACK_ID: LVL230K

networks:
  devnet:
