events {}

http {
    upstream fastapi_backend {
        server broker:8000;
        server broker:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://fastapi_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # For identifiying balanced node
            proxy_set_header X-Container-ID $hostname;
        }
    }
}
